name: Neoland Ci 

# start run the workflow when someone make push on the main branch 

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    # gitubu create temp machine linux
    runs-on: ubuntu-latest
    steps:
      # gitubu clone the repo in the temp machine
      - uses: actions/checkout@v2j
      # install node js in the temp machine
      - name: Use Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'
      # install dependencies 
      - name: Install dependencies
        run: npm install
      # run test 
      - name: Run Build
        run: npm run build
      - name: Run Lint
        run: npm run lint

        